### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by cuge1995** [kentfuji/NeuralEmbedding#1]
when run classify.py

NeuralEmbedding/utility.py", line 41, in prepSamplePoints
    b1 = loadRandomWeight(weight_name, dim, False)
TypeError: loadRandomWeight() takes 2 positional arguments but 3 were given

**Comment by kentfuji** [comment]
I've removed the third unnecessary argument

**Comment by cuge1995** [comment]
---- train data 0 ----
**** Calculating Distance ****
/home/cuge/Documents/point/NeuralEmbedding/process.py:10: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  data_file = h5py.File(h5name)
Traceback (most recent call last):
  File "/home/cuge/.local/lib/python3.6/site-packages/h5py/_hl/files.py", line 199, in make_fid
    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '../EllipsoidQuery/RSCNNEQ/data/modelnet40_ply_hdf5_2048/data/modelnet40_ply_hdf5_2048/ply_data_train0.h5.h5', errno = 2, error message = 'No such file or directory', flags = 1, o_flags = 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cuge/.local/lib/python3.6/site-packages/h5py/_hl/files.py", line 202, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '../EllipsoidQuery/RSCNNEQ/data/modelnet40_ply_hdf5_2048/data/modelnet40_ply_hdf5_2048/ply_data_train0.h5.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "classify.py", line 86, in <module>
    process.calcDistField(os.path.join(SAVE_DIR, point_name), os.path.join(DATA_DIR, original_name), os.path.join(SAVE_DIR, svd_name))
  File "/home/cuge/Documents/point/NeuralEmbedding/process.py", line 10, in calcDistField
    data_file = h5py.File(h5name)
  File "/home/cuge/.local/lib/python3.6/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/home/cuge/.local/lib/python3.6/site-packages/h5py/_hl/files.py", line 204, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 108, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = '../EllipsoidQuery/RSCNNEQ/data/modelnet40_ply_hdf5_2048/data/modelnet40_ply_hdf5_2048/ply_data_train0.h5.h5', errno = 2, error message = 'No such file or directory', flags = 15, o_flags = c2)

**Comment by cuge1995** [comment]
still another one exist

**Comment by kentfuji** [comment]
I think this has to do with the directory and filenames.
>Please modify both train_files.txt and test_files.txt to only include file names without the extension, e.g. ply_data_train0

**Comment by kentfuji** [comment]
Please don't include the directory or the file extension in the list

**Comment by cuge1995** [comment]
It should without "data/modelnet40_ply_hdf5_2048/" too in the original file

**Comment by cuge1995** [comment]
Still another bug

NeuralEmbedding/process.py", line 23, in calcDistField
    distancesgpu = numpy.zeros((data_dim, data.shape[1], sample_size))
MemoryError: Unable to allocate 32.0 GiB for an array with shape (2048, 2048, 1024) and data type float64

**Comment by kentfuji** [comment]
Unfortunately, I would recommend splitting the files into smaller bits, as I've taken a memory consuming, but efficient way to process distance fields.
>Preprocessing data into ELM requires memory space. We recommend splitting the data files into smaller batches if the processing fails.

**Comment by kentfuji** [comment]
or if you want to just see if it works, please try running with smaller sample_size and dim in the arguments. It won't provide the best results, but would consume less memory space!

**Comment by cuge1995** [comment]
thanks

**Comment by cuge1995** [comment]
what's the devices did you used ?   like the RAM and GPU ?

**Comment by kentfuji** [comment]
We used a V100 machine equipped with at least 128GB memory.
